backend:
  name: git-gateway
  branch: test
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: oliancho
    api_key: 745898391849235
    default_transformations:
      - - fetch_format: auto
          width: 1200
          quality: auto
          crop: limit
collections:
  - name: 'japanese__posts'
    label: 'ブログ/日本語'
    folder: 'contents/ja/posts'
    create: true
    slug: '{{slug}}'
    preview_path: 'ja/posts/{{slug}}'
    filter: { field: 'language', value: 'ja' }
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string', required: true }
      - {
          label: 'タグ',
          name: 'tag',
          widget: 'select',
          required: false,
          options: ['life', 'web', 'japanese', 'glutenFree'],
        }
      - {
          label: '著者',
          name: 'author',
          widget: 'select',
          required: true,
          options: ['Davide', 'Gobu'],
        }
      - {
          label: '言語',
          name: 'language',
          widget: 'hidden',
          required: true,
          default: 'ja',
        }
      - { label: '作成日', name: 'date', widget: 'date', required: true }
      - { label: '更新日', name: 'update', widget: 'date', required: false }
      - {
          label: 'サムネイル',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - {
          label: '概要',
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{15,45}', '15 ~ 45字以内'],
        }
      - { label: '本文', name: 'body', widget: 'markdown', required: true }

  - name: 'english__posts'
    label: 'Blog/English'
    folder: 'contents/en/posts/'
    create: true
    slug: '{{slug}}'
    preview_path: 'posts/{{slug}}'
    filter: { field: 'language', value: 'en' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Tag',
          name: 'tag',
          widget: 'select',
          required: false,
          options: ['life', 'web', 'japanese', 'glutenFree'],
        }
      - {
          label: 'author',
          name: 'author',
          widget: 'select',
          required: true,
          options: ['Gobu', 'Davide'],
        }
      - {
          label: 'Language',
          name: 'language',
          widget: 'hidden',
          required: true,
          default: 'ja',
        }
      - {
          label: 'Published date',
          name: 'date',
          widget: 'date',
          required: true,
        }
      - {
          label: 'Updated date',
          name: 'update',
          widget: 'date',
          required: false,
        }
      - {
          label: 'Thumbnail',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - {
          label: 'Summary',
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{15,45}', 'Between 15 ~ 45 charactors'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
