backend:
  name: git-gateway
  branch: test
publish_mode: editorial_workflow
media_folder: 'static/images'
public_folder: '/images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string', required: true }
      - { label: 'タグ', name: 'type', widget: 'string', required: false }
      - {
          label: '著者',
          name: 'author',
          widget: 'string',
          required: true,
          default: 'Gobu',
        }
      - {
          label: '言語',
          name: 'language',
          widget: 'string',
          required: true,
          default: 'ja',
        }
      - { label: '作成日', name: 'date', widget: 'date', required: true }
      - { label: '更新日', name: 'update', widget: 'date', required: false }
      - {
          label: 'サムネイル',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      # - {label: "概要", name: summary, widget: text, required: true}
      #, pattern: ['.{20,60}', "20 ~ 60字以内"] -add this to summary for limitation.
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
